// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzYIZVeeuFKw3TYKGUURhXVfGgQ2Htm78',
    appId: '1:173894022173:web:6820f5de1797fc429fc2f4',
    messagingSenderId: '173894022173',
    projectId: 'trueneighbour',
    authDomain: 'trueneighbour.firebaseapp.com',
    storageBucket: 'trueneighbour.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZDzZaVTfC-Efc9SgqT7pZDh7uBgxqGrE',
    appId: '1:173894022173:android:8d945c744c4dd16c9fc2f4',
    messagingSenderId: '173894022173',
    projectId: 'trueneighbour',
    storageBucket: 'trueneighbour.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3ozwdOM3CA36dV91CRkq91_dHTp70haQ',
    appId: '1:173894022173:ios:f4c145b24aad03919fc2f4',
    messagingSenderId: '173894022173',
    projectId: 'trueneighbour',
    storageBucket: 'trueneighbour.firebasestorage.app',
    iosBundleId: 'com.example.trueNeighbour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3ozwdOM3CA36dV91CRkq91_dHTp70haQ',
    appId: '1:173894022173:ios:f4c145b24aad03919fc2f4',
    messagingSenderId: '173894022173',
    projectId: 'trueneighbour',
    storageBucket: 'trueneighbour.firebasestorage.app',
    iosBundleId: 'com.example.trueNeighbour',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzYIZVeeuFKw3TYKGUURhXVfGgQ2Htm78',
    appId: '1:173894022173:web:da486442b83131cb9fc2f4',
    messagingSenderId: '173894022173',
    projectId: 'trueneighbour',
    authDomain: 'trueneighbour.firebaseapp.com',
    storageBucket: 'trueneighbour.firebasestorage.app',
  );
}
